version: 1.0.{build}

branches:
  only:
  - master
  - windows-port

os: Visual Studio 2015

clone_folder: c:\dev\tarantool

platform: x64

environment:
  matrix:
    - Generator: "Visual Studio 14 2015 Win64"
      Config: Debug

    - Generator: "Visual Studio 14 2015 Win64"
      Config: Release

build_script:
  - cd c:\dev\tarantool
  - mkdir build
  - cd build
  - cmake .. -G "%Generator%" -DSMALL_EMBEDDED=1
  - msbuild /m /p:Configuration=%Config% /p:Platform="Win32" small.sln

 
test_script:
  - ctest -C %Config% -VV
